language: java
env:
  global:
  - SONATYPE_USERNAME=admin
  - secure: yoMAsBfQLdulJ76f6V8eVapqnlJNqS9SIrna2Q0hSGZYAFDEw3lEodaS+LA+blHJh7kiaoYGJ6xhekp09t+sZW32zvXTvNS10h5srKBr1gIrYVEB1LpQhAtPWwSE+yQIdqqyb1s0GtcohojXz9awhYCHnFBXRjE5oEdtOqzReqQMSA5WfF2UUpzwxrT8Js3cDCQJdBZwLN/lkmoGCz65HLslOtoAUlKaEseGj6uzZVcMvmNVBKfw7lWuigZJriW7HPA+7XIWQKa74QuLaiC/g9De5vJpLu8MdHRDY5EAzbr5fwT50+eXjVzFHmywXiH60/ubPeLQS0fVbvbbIx//CJt3Km20lPSJw84APOoNZ0aDShkgquwc5dMD5fi8WM/hfM0KXSfzA8sK/QhaIuhH3jQBbr1WAYuYmoaZH3uBAVJ3TPmDwhZzBcMJ4hTb1uMKwqR1anWmBhABGfAkO1bSFMLK3awegEiTwBo+ppPkG4ZbFWruPQv23lDDtD9CfiGUx926HQ3VfTUCKLLCD1AWIEPu/RXCX40Q06ZnwfnKYn4kBPG2PuLG1KdJBVO+r1TB5MmM/ZhD4ddVkScYzbCuNuctLoRAwoWQoLO5NAS1iwxIl8uxXpnHzHVLLkj6cu9dMfiY5p3LkC+VDUKuINQsEooGPw7CtYkXpZpaf2HTxj8=
after_success:
- mvn deploy --settings travis-settings.xml -DskipTests=true -B
